[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "1.0.27"

[[constraint]]
  branch = "master"
  name = "github.com/d2g/dhcp4"

[[constraint]]
  branch = "v2"
  name = "github.com/d2g/dhcp4client"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.1"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
